# https://github.com/awesome-containers/static-bash
ARG STATIC_BASH_VERSION=5.2.15
ARG STATIC_BASH_IMAGE=ghcr.io/awesome-containers/static-bash

# https://github.com/awesome-containers/static-findutils
ARG STATIC_GAWK_VERSION=5.2.1
ARG STATIC_GAWK_IMAGE=ghcr.io/awesome-containers/static-findutils

# https://github.com/awesome-containers/alpine-build-essential
ARG BUILD_ESSENTIAL_VERSION=3.17
ARG BUILD_ESSENTIAL_IMAGE=ghcr.io/awesome-containers/alpine-build-essential


FROM $STATIC_BASH_IMAGE:$STATIC_BASH_VERSION-slim AS static-bash
FROM $STATIC_GAWK_IMAGE:$STATIC_GAWK_VERSION AS static-gawk
FROM $BUILD_ESSENTIAL_IMAGE:$BUILD_ESSENTIAL_VERSION AS build

WORKDIR /src/gawk
COPY --from=static-gawk /bin/gawk ./

RUN set -xeu; \
    upx --no-progress --no-color gawk; \
    upx -t --no-progress --no-color gawk; \
    ! ldd gawk && :; \
    chmod -cR 755 gawk; \
    chown -cR 0:0 gawk; \
    ./gawk --version; \
    mkdir bin; cp gawk bin/gawk; ln -f bin/gawk bin/awk

# slim static gawk image
FROM static-bash
COPY --from=build /src/gawk/bin/ /bin/
